
import pandas as pd
gt_df_zh_ref = pd.DataFrame([
    {
        "topic":"us_fed_meeting_may_2025",
        "generated":"",
        "references":[
            "新浪财经称5月议息或按兵不动，概率97%。",
            "东方财富网称投资者关注鲍威尔记者会。",
            "新浪财经前瞻称降息概率仅3.2%。",
            "东方财富评论提到6月降息押注。",
            "证券时报分析鲍威尔或回击干预论。"
        ],
    },
    {
        "topic":"trump_third_term_tariffs",
        "generated":"",
        "references":[
            "法广中文网报道特朗普宣布100%关税。",
            "联合早报称关税保护文化安全。",
            "华尔街日报中文网称特朗普不谋求三连任。",
            "央视网评论称或引发盟友报复。",
            "观察者网梳理潜在接班人。"
        ],
    },
    {
        "topic":"bahia_brazil_flood_alert_may_2025",
        "generated":"",
        "references":[
            "新华社称暴雨已致75人遇难。",
            "央视新闻报道宣布紧急状态。",
            "新华网图文显示334座城市受影响。",
            "Swissinfo中文网称史上最大气候灾难。",
            "南美侨报统计指出萨尔瓦多高风险。"
        ],
    },
    {
        "topic":"israel_gaza_takeover_plan",
        "generated":"",
        "references":[
            "中新网称以色列批准占领加沙计划。",
            "新华社报道征召预备役。",
            "中国网称行动将摧毁隧道网络。",
            "央视新闻指出援助通道担忧。",
            "半岛电视台中文网分析战争罪风险。"
        ],
    },
    {
        "topic":"tech_sector_layoffs_2025",
        "generated":"",
        "references":[
            "36氪称5万人被裁。",
            "时代周报披露微创软件裁员。",
            "新浪财经指出裁员真实性。",
            "联合早报分析重组业务。",
            "36氪称英特尔计划最大裁员。"
        ],
    },
])
